# Lec 04-1. multi-variable linear regression을 Tensorflow 에서 구현하기

In [1]:
import tensorflow as tf

## Hypothesis without matrix

In [3]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, y: y_data})
    if step % 100 == 0:
        print(f'{step} step\n  Cost: {cost_val}\n  Prediction: {hy_val}\n')

0 step
  Cost: 62215.58203125
  Prediction: [-71.54681  -80.762856 -82.81272  -84.13084  -65.19802 ]

100 step
  Cost: 10.333416938781738
  Prediction: [149.73466 185.24025 179.26546 201.2524  137.71626]

200 step
  Cost: 10.262008666992188
  Prediction: [149.71536 185.25491 179.26141 201.23463 137.74811]

300 step
  Cost: 10.1920747756958
  Prediction: [149.69676 185.2692  179.25764 201.21707 137.77933]

400 step
  Cost: 10.123557090759277
  Prediction: [149.67883 185.28304 179.25407 201.1997  137.80995]

500 step
  Cost: 10.056477546691895
  Prediction: [149.6615  185.29636 179.25066 201.18246 137.83989]

600 step
  Cost: 9.990674018859863
  Prediction: [149.64484 185.30925 179.24742 201.16542 137.86926]

700 step
  Cost: 9.926172256469727
  Prediction: [149.62878 185.32176 179.2444  201.14856 137.89804]

800 step
  Cost: 9.862924575805664
  Prediction: [149.61331 185.33386 179.24156 201.1319  137.92627]

900 step
  Cost: 9.800724983215332
  Prediction: [149.5984  185.34557 179.23886

실제 y 값: [152, 185, 180, 196, 142]  
  
Matrix 없으면 코드가 더러워진다

## Hypothesis with matrix

In [9]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

# placeholder for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = \
        sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    
    if step % 100 == 0:
        print(f'{step} step\n  Cost: {cost_val}\n  Prediction:\n{hy_val}\n')

0 step
  Cost: 111693.7734375
  Prediction:
[[-137.52034]
 [-176.87514]
 [-168.22125]
 [-184.51347]
 [-136.64798]]

100 step
  Cost: 26.079437255859375
  Prediction:
[[158.78397]
 [179.63939]
 [182.86156]
 [197.82892]
 [135.35881]]

200 step
  Cost: 24.712373733520508
  Prediction:
[[158.58862]
 [179.77333]
 [182.80174]
 [197.78525]
 [135.53494]]

300 step
  Cost: 23.4173583984375
  Prediction:
[[158.3985 ]
 [179.9037 ]
 [182.74355]
 [197.74275]
 [135.70639]]

400 step
  Cost: 22.190670013427734
  Prediction:
[[158.21347]
 [180.0306 ]
 [182.6869 ]
 [197.70134]
 [135.87325]]

500 step
  Cost: 21.028743743896484
  Prediction:
[[158.0334 ]
 [180.15408]
 [182.63179]
 [197.66109]
 [136.03566]]

600 step
  Cost: 19.928081512451172
  Prediction:
[[157.85814]
 [180.27426]
 [182.57811]
 [197.62184]
 [136.19371]]

700 step
  Cost: 18.885540008544922
  Prediction:
[[157.6876 ]
 [180.39125]
 [182.52594]
 [197.58368]
 [136.34758]]

800 step
  Cost: 17.897945404052734
  Prediction:
[[157.52159]
 [18

# Lec 04-2. TensorFlow로 파일에서 데이터 읽어오기

In [4]:
import numpy as np
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [5]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [7]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X:x_data, Y:y_data})
    if step % 100 == 0:
        print(f'{step} step\n  Cost: {cost_val}\n  Prediction:\n{hy_val}\n')

0 step
  Cost: 20344.2734375
  Prediction:
[[22.048063 ]
 [21.619787 ]
 [24.096693 ]
 [22.293005 ]
 [18.633902 ]
 [ 7.2669735]]

100 step
  Cost: 6.353769302368164
  Prediction:
[[155.79639]
 [182.60619]
 [182.59769]
 [194.92845]
 [141.45721]
 [ 97.87128]]

200 step
  Cost: 6.034921169281006
  Prediction:
[[155.69016 ]
 [182.65692 ]
 [182.55382 ]
 [194.90393 ]
 [141.5211  ]
 [ 97.975174]]

300 step
  Cost: 5.7362751960754395
  Prediction:
[[155.5874 ]
 [182.70596]
 [182.51134]
 [194.88031]
 [141.58273]
 [ 98.0758 ]]

400 step
  Cost: 5.456491947174072
  Prediction:
[[155.48799 ]
 [182.75337 ]
 [182.47021 ]
 [194.8576  ]
 [141.6422  ]
 [ 98.173256]]

500 step
  Cost: 5.194362163543701
  Prediction:
[[155.39178]
 [182.79918]
 [182.4304 ]
 [194.83575]
 [141.69955]
 [ 98.26765]]

600 step
  Cost: 4.948755264282227
  Prediction:
[[155.29875]
 [182.84352]
 [182.39188]
 [194.81474]
 [141.75491]
 [ 98.35909]]

700 step
  Cost: 4.718599796295166
  Prediction:
[[155.2087 ]
 [182.88632]
 [182.354

In [10]:
# Ask my score
print(f"Your score will be\n  {sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]})}")
                
print(f"Other score will be\n  {sess.run(hypothesis, feed_dict={X:[[60, 70, 110], [90, 100, 80]]})}")

Your score will be
  [[171.15341]]
Other score will be
  [[106.725494]
 [197.8313  ]]


## Queue Runners

file이 아주 클 때 활용

![](lec04.assets/image1.png)

### queue runner 사용법

In [49]:
# make filename queue
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv', 'data-02-test-score.csv'],
    shuffle=False, name='filename_queue')

# reader & read filename queue
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# parse value (decode)
record_defaults = [[0.], [0.], [0.], [0.]]  # data type 및 default 값 정의
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[:-1], xy[-1]], batch_size=3)  # batch_size: 10개씩 가져온다
    
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    _cost, _hy, _ = sess.run(
                    [cost, hypothesis, train],
                    feed_dict={X:x_batch, Y:y_batch})
    if step % 100 == 0:
        print(f'{step} step\n  Cost: {_cost}\n  Prediction:\n{_hy}\n')

coord.request_stop()
coord.join(threads)

ValueError: Cannot feed value of shape (3,) for Tensor 'Placeholder_31:0', which has shape '(?, 1)'