# Cross validation

## Introduction

모델을 만들 때는 주어진 학습데이터만 이용해서 모델을 학습한다. 이때, 학습데이터로 모델을 평가한 수치가 새로운 데이터(unseen)에 대한 모델의 성능을 반영한다고 할수없다. 즉 train error와 test error가 다를 수 있다. 아래 그림을 보면 복잡한 모델을 설계할수록 Train error값은 계속 감소하지만, Test error는 어느순간 증가하는 현상을 볼 수 있다.

<br>
<div align="center">
    <img src="https://user-images.githubusercontent.com/30274701/67631911-e717c180-f8df-11e9-88ff-9eea786aca24.png" width="650">
    <br>
    <font color=gray><i>Train and Test error</i><font>
</div>
<br>

이러한 상황에서 모델이 새로운 데이터에도 좋은 성능을 낼 수 있는지 추정하려고 한다. 크게 두가지 방법이 사용된다.

1. hold-out method
2. cross validation

## 1. Hold-out Method

가장 간단한 방법으로 기존의 학습데이터를 train과 validation으로 나눈다.<br> 
이렇게 나눈 데이터를 가지고 모델을 학습하고 평가한다.
훈련데이터로 모델을 학습하고, 테스트 데이터로 모델의 성능을 증가시키는 선택을 반복하게 된다.
하지만 모델을 선택하는 동안 동일한 테스트 데이터를 계속 재사용한다면, 이 테스트 데이터는 테스트데이터로써의
효용가치가 떨어지고, 훈련데이터화 될 것이다. 결국 데이터는 오버피팅 된다.<br>

홀드아웃 교차검증의 단점은, 데이터를 위와 같이 나눈 방식 자체가 성능 추정에 민감한 영향을 미친다는 것이다.
만약 데이터셋 전체가 개수가 크지 않다면, 이러한 분할은 치명적일 수 있다.
즉 홀드아웃 셋을 만들어 내는 것 자체에 대단한 신경을 써야한다는 것이다.

## 2. Cross validation

학습 데이터를 train과 validation으로 나누는 과정을 여러번 반복한다. 이때 validation set을 정하는 방법에 따라 크게 두 가지가 있다.

### 2-1. LOOCV(Leave-one-out CV)
* 하나의 데이터만 validation으로 사용하고 나머지로 학습하는 방법이다.
* low bias, high variance 방향으로 모델이 학습된다. 분산이 높은 알고리즘은 트레이닝 셋에 좋은 성능을 보여주지만, 큰 노이즈나 이상치(outlier)에도 과적합(overfitting)될 위험이 있다. 즉 분산이 높고(high variance) 편향이 작은(low bias) 모델은 일반적으로 복잡하게 만들어 진다.

* 계산량이 매우 많다.

<br>
<div align="center">
    <img src="https://t2.daumcdn.net/thumb/R720x0/?fname=http://t1.daumcdn.net/brunch/service/user/4Jol/image/UU3M0NRsXYP_IkJTGPwfksb_eAQ" width="400">
    <br>
    <font color=gray><i>LOOCV(Leave-one-out CV)</i><font>
</div>
<br>


### 2-2 K-fold

* 전체 데이터를 K개로 나누고, 한 부분을 validation으로, 나머지를 train으로 사용하는 방법이다.
* high bias, low variance 방향으로 모델이 학습된다. LOOCV보다 train 데이터의 수가 적어지므로 과소적합(underfitting)될 수있으나, 다른 train 데이터로 학습하는 과정에서 일반화된 모델이 만들어지게 되어 low variance를 보이게 된다.

<br>
<div align="center">
    <img src="https://t3.daumcdn.net/thumb/R720x0/?fname=http://t1.daumcdn.net/brunch/service/user/4Jol/image/mpp4aoUMbP8f-FJtBC-cSinhBBg" width="400">
    <br>
    <font color=gray><i>K-fold</i><font>
</div>
<br>

K-fold로 모델을 학습하게 되면, 총 K개의 모델 validation 값이 생성되고 이 결과값을 이용해서 모델의 성능을 평가하게 된다. 

1. K개의 validation 값(error)의 평균과 표준편차를 이용해서 모델을 평가한다. 이때, K개의 값은 서로 비슷해야 한다. 만약, 서로 비슷하지 않다면 테스트에서 안정적인 예측치를 얻기 어렵다고 불 수 있다.<br>

2. K개에서 얻은 validation set을 하나로 합쳐 전체 데이터셋의 예측치처럼 사용한다. 즉, K fold의 validation set을 합치면 전체 데이터와 일치하므로 이 예측값을 이용해서 모델의 Loss값(ex. RMSE)을 계산해서 모델을 평가한다. 이 방법을 OOF(out-of-fold)라고 한다.

#### 편향-분산 트레이드오프, 위키백과 


_편향-분산 트레이드오프는 지도 학습에서 매우 중요한 문제이다. 모델을 선택할 때(model selection), 트레이닝 데이터의 규칙을 정확하게 포착하는 것 뿐만이 아니라, 보이지 않는 범위에 대해서 일반화(generalization)까지 하는 것이 이상적이다. 하지만 안타깝게도 이 둘을 동시에 완전히 성취하는것은 사실상 불가능하다. 고분산 학습 알고리즘은 트레이닝 셋을 잘 표현하기는 하지만, 지나치게 큰 노이즈나 아예 부적절한 트레이닝 데이터까지 과적합(overfitting)할 위험이 있다. 반대로 고편향 학습 알고리즘은 과적합(overfitting) 문제가 거의 없는 단순한 모델을 제시하지만 트레이닝 데이터로부터 중요한 규칙성을 제대로 포착하지 못하는 과소적합(underfitting) 문제가 발생한다._

_편향값이 낮은 모델은 일반적으로 더 복잡하기 때문에(예: 더 높은 차수의 회귀 다항식) 트레이닝 셋을 더 정확히 표현한다. 하지만 모델링 과정에서 커다란 노이즈 성분까지 반영할 가능성이 있고, 그런 경우에는 더 복잡함에도 불구하고 덜 정확한 추론을 하게 된다. 반대로 편향값이 높은 모델의 경우 간단한(낮은 차수의 회귀 다항식) 경향이 있는데, 트레이닝 셋의 데이터를 모델에 충분히 포함하지 못해 분산값이 낮게 나올 수가 있다._

<br>
<div align="center">
    <img src="https://lh3.googleusercontent.com/K3fjd0dVZbfXCo5LHFZVfSdfq5UBM-iLniMQZ3V4TqByZON9LvmtYazglVlcN9kyVXc5ZpZT2BJhd_yLWzZ8kcYku8yyEn2PaHdEn-JBobtPcWWG26WVUXdClvTf_o9nv835wghYCoY" width="600">
    <br>
    <font color=gray><i>Model bias and variance</i><font>
</div>
<br>



[kaggle Housing Prices Competition for Kaggle Learn Users](https://www.kaggle.com/c/home-data-for-ml-course)의 데이터를 사용해서 실습해보자.

In [98]:
import numpy as np
import pandas as pd

import warnings
warnings.simplefilter('ignore')

In [63]:
# Read the data
train_data  = pd.read_csv('train.csv')
test_data  = pd.read_csv('test.csv')

# Remove rows with missing target, separate target from predictors
train_data.dropna(axis=0, subset=['SalePrice'], inplace=True)
y = train_data.SalePrice              
train_data.drop(['SalePrice'], axis=1, inplace=True)

# Select numeric columns only
numeric_cols = [cname for cname in train_data.columns if train_data[cname].dtype in ['int64', 'float64']]
X = train_data[numeric_cols].copy()
X_test = test_data[numeric_cols].copy()

#Delete null columns
X.drop(X.isnull().sum()[X.isnull().sum() > 0].index, axis=1, inplace=True)

In [64]:
X.head()

Id  MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
0   1          60     8450            7            5       2003          2003   
1   2          20     9600            6            8       1976          1976   
2   3          60    11250            7            5       2001          2002   
3   4          70     9550            7            5       1915          1970   
4   5          60    14260            8            5       2000          2000   

   BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  ...  GarageArea  WoodDeckSF  \
0         706           0        150  ...         548           0   
1         978           0        284  ...         460         298   
2         486           0        434  ...         608           0   
3         216           0        540  ...         642           0   
4         655           0        490  ...         836         192   

   OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MiscVal  \
0           61              0          0            0         0        0   
1            0              0          0            0         0        0   
2           42              0          0            0         0        0   
3           35            272          0            0         0        0   
4           84              0          0            0         0        0   

   MoSold  YrSold  
0       2    2008  
1       5    2007  
2       9    2008  
3       2    2006  
4      12    2008  

[5 rows x 34 columns]

### 1. train_test_split

* 비율로 train과 test셋을 나누는 방법
* [sklearn.model_selection.train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
x_tr, x_val= train_test_split(X, test_size=0.33, random_state=42)
print('{} -> train : {}, val : {}'.format(X.shape, x_tr.shape, x_val.shape))

x_tr, x_val, y_tr, y_val = train_test_split(X, y, test_size=0.33, random_state=42)
print('{} -> train : {}, val : {}'.format(X.shape, x_tr.shape, x_val.shape))

(1460, 34) -> train : (978, 34), val : (482, 34)
(1460, 34) -> train : (978, 34), val : (482, 34)


### 2. LeaveOneOut

In [67]:
from sklearn.model_selection import LeaveOneOut

In [68]:
loo = LeaveOneOut()
print(loo.get_n_splits(X))

c = 0
for train_index, test_index in loo.split(X):
    print(train_index, test_index)
    
    c+=1
    if c ==3 :
        break

1460
[   1    2    3 ... 1457 1458 1459] [0]
[   0    2    3 ... 1457 1458 1459] [1]
[   0    1    3 ... 1457 1458 1459] [2]


### 3. K-fold

* `sklearn.model_selection.KFold` : 데이터셋을 K개로 나눔
* `sklearn.model_selection.StratifiedKFold` : class가 골고루 포함될 수 있도록 데이터를 k개로 나눔
* `sklearn.model_selection.TimeSeriesSplit` : 데이터의 앞부분부터 점차 늘려가는 방법
* [Visualizing cross-validation behavior in scikit-learn](https://scikit-learn.org/stable/auto_examples/model_selection/plot_cv_indices.html#sphx-glr-auto-examples-model-selection-plot-cv-indices-py)


In [69]:
from sklearn.model_selection import KFold

In [70]:
folds = KFold(n_splits=5, shuffle=True, random_state=42)

In [71]:
for fold, (trn_idx, val_idx) in enumerate(folds.split(X, y)):
    print(fold)
    print(trn_idx.shape, val_idx.shape)
    display(X.iloc[val_idx].head())
    break

0
(1168,) (292,)


Id  MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  \
15  16          45     6120            7            8       1929   
23  24         120     4224            5            7       1976   
29  30          30     6324            4            6       1927   
30  31          70     8500            4            4       1920   
32  33          20    11049            8            5       2007   

    YearRemodAdd  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  ...  GarageArea  \
15          2001           0           0        832  ...         576   
23          1976         840           0        200  ...         572   
29          1950           0           0        520  ...         240   
30          1950           0           0        649  ...         250   
32          2007           0           0       1234  ...         484   

    WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  \
15          48          112              0          0            0         0   
23         100          110              0          0            0         0   
29          49            0             87          0            0         0   
30           0           54            172          0            0         0   
32           0           30              0          0            0         0   

    MiscVal  MoSold  YrSold  
15        0       7    2007  
23        0       6    2007  
29        0       5    2008  
30        0       7    2008  
32        0       1    2008  

[5 rows x 34 columns]

모델을 학습시키고 성능을 평가해봅시다.

In [72]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression

In [102]:
%%time
loo = LeaveOneOut()
loo_score = []
print(loo.get_n_splits(X))
c = 0

for trn_idx, val_idx in loo.split(X):
    model = RandomForestRegressor()
    model.fit(X.iloc[trn_idx], y.iloc[trn_idx])
    loo_score.append(model.score(X.iloc[val_idx], y.iloc[val_idx])) #R square error
    
    c+=1
    if c == 20:
        break
print(loo_score)

1460
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Wall time: 13.3 s


In [103]:
%%time
folds = KFold(n_splits=5, shuffle=True, random_state=42)
k_score = []

for fold, (trn_idx, val_idx) in enumerate(folds.split(X, y)):
    model = RandomForestRegressor()
    model.fit(X.iloc[trn_idx], y.iloc[trn_idx])
    k_score.append(model.score(X.iloc[val_idx], y.iloc[val_idx])) #R square error
    
print(k_score)

[0.8826139061319215, 0.8796500637990518, 0.57515509195766, 0.8398289393769451, 0.8694921875779349]
Wall time: 535 ms


### 4. cross_val_score

* 모델을 평가할 때 사용
* `model` parameter 위치에 학습이 안된 model이 들어가게 되면 학습과 평가가 동시에 진행된다.

In [ ]:
from sklearn.model_selection import cross_val_score

In [96]:
#model = RandomForestRegressor()
scores_2 = cross_val_score(model, X, y, cv=4)
print(scores_2)

[0.85302614 0.83497182 0.86125101 0.80207018]


참고 사이트 

* [Cross Validation and the Bias-Variance tradeoff (for Dummies)](https://codesachin.wordpress.com/2015/08/30/cross-validation-and-the-bias-variance-tradeoff-for-dummies/)
* [교차검증(Cross Validation)을 통한 모델 평가방법](https://yamalab.tistory.com/44)
* [Bias and Variance (편향과 분산)](https://www.opentutorials.org/module/3653/22071)
* [편향-분산 트레이드오프, 위키백과](https://ko.wikipedia.org/wiki/%ED%8E%B8%ED%96%A5-%EB%B6%84%EC%82%B0_%ED%8A%B8%EB%A0%88%EC%9D%B4%EB%93%9C%EC%98%A4%ED%94%84)
