# Lec 09. Neural Net for XOR

In [3]:
import tensorflow as tf
import numpy as np

## XOR with Logistic Regression

In [4]:
# XOR dataset
x_data = np.array([[0,0], [0,1], [1,0], [1,1]], dtype=np.float32)
y_data = np.array([[0],   [1],   [1],   [0]], dtype=np.float32)

In [11]:
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize Tensorflow variables
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 100 == 0:
            print(f'{step} step\ncost: {sess.run(cost, feed_dict={X:x_data, Y:y_data})}\n{sess.run(W)}\n')
            
    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    print(f'\nhypothesis:\n{h}\nCorrect:\n{c}\nAccuracy: {a}')

0 step
cost: 1.1524146795272827
[[-1.6520821 ]
 [-0.28142795]]

100 step
cost: 0.7049669027328491
[[-0.57611686]
 [ 0.21662103]]

200 step
cost: 0.6967628598213196
[[-0.32193413]
 [ 0.10356742]]

300 step
cost: 0.6943176984786987
[[-0.1873467 ]
 [ 0.04028057]]

400 step
cost: 0.6935430765151978
[[-0.11046875]
 [ 0.01118244]]

500 step
cost: 0.6932882070541382
[[-0.06600873]
 [-0.00101328]]

600 step
cost: 0.6932002305984497
[[-0.03998102]
 [-0.00525838]]

700 step
cost: 0.6931681632995605
[[-0.02454251]
 [-0.00599303]]

800 step
cost: 0.6931557655334473
[[-0.01525997]
 [-0.00535056]]

900 step
cost: 0.6931508183479309
[[-0.00960258]
 [-0.00430884]]

1000 step
cost: 0.6931487917900085
[[-0.00610887]
 [-0.00328088]]

1100 step
cost: 0.6931479573249817
[[-0.00392424]
 [-0.0024135 ]]

1200 step
cost: 0.6931474208831787
[[-0.0025424 ]
 [-0.00173534]]

1300 step
cost: 0.6931473612785339
[[-0.00165924]
 [-0.0012281 ]]

1400 step
cost: 0.6931472420692444
[[-0.00108961]
 [-0.00085925]]

1500 st

Logistic Regression 을 이용한 XOR 문제 풀기...  <br>
그런데 <u>**잘 작동하지 않았다.**</u> (accuracy 0.5)

## XOR with Neural Net
이번엔 Neural Net 을 이용해 XOR 문제를 풀어보자!

In [13]:
# 1st layer
W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

# 2nd layer
W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

위 코드는 아래 그림과 같다
![](lec09.assets/image1.png)

In [16]:
# cost/loss function
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y) * tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 100 == 0:
            print(f'{step} step\nCost: {sess.run(cost, feed_dict={X:x_data, Y:y_data})}\nWeight:\n{sess.run([W1, W2])}')
    
    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X:x_data, Y:y_data})
    print(f'\nHypothesis:\n{h}\nCorrect:\n{c}\nAccuracy:\n{a}')
            

0 step
Cost: 0.6991653442382812
Weight:
[array([[-0.35888052, -1.2310377 ],
       [ 0.09866738, -1.0999074 ]], dtype=float32), array([[-0.9549873],
       [ 0.6834596]], dtype=float32)]
100 step
Cost: 0.6915502548217773
Weight:
[array([[-0.3794721 , -1.1688247 ],
       [ 0.03341886, -1.0331584 ]], dtype=float32), array([[-0.91528714],
       [ 0.7300425 ]], dtype=float32)]
200 step
Cost: 0.6899814605712891
Weight:
[array([[-0.39013833, -1.1356702 ],
       [-0.01726294, -0.99892503]], dtype=float32), array([[-0.9261465],
       [ 0.7299839]], dtype=float32)]
300 step
Cost: 0.6887247562408447
Weight:
[array([[-0.40408942, -1.1170646 ],
       [-0.06833107, -0.9816976 ]], dtype=float32), array([[-0.9419014],
       [ 0.7433142]], dtype=float32)]
400 step
Cost: 0.6875463128089905
Weight:
[array([[-0.42259595, -1.1094992 ],
       [-0.12133651, -0.9773947 ]], dtype=float32), array([[-0.96162057],
       [ 0.7669891 ]], dtype=float32)]
500 step
Cost: 0.6863068342208862
Weight:
[array([[-0

4700 step
Cost: 0.052051808685064316
Weight:
[array([[-5.2969365, -4.3331103],
       [-5.2953115, -4.332632 ]], dtype=float32), array([[-8.249456],
       [ 7.45059 ]], dtype=float32)]
4800 step
Cost: 0.04980633035302162
Weight:
[array([[-5.329407 , -4.3649836],
       [-5.327835 , -4.3645244]], dtype=float32), array([[-8.328832 ],
       [ 7.5368304]], dtype=float32)]
4900 step
Cost: 0.0477319210767746
Weight:
[array([[-5.360434 , -4.395498 ],
       [-5.35891  , -4.3950567]], dtype=float32), array([[-8.405308 ],
       [ 7.6198473]], dtype=float32)]
5000 step
Cost: 0.045810796320438385
Weight:
[array([[-5.390126 , -4.4247484],
       [-5.3886466, -4.424327 ]], dtype=float32), array([[-8.479074],
       [ 7.699851]], dtype=float32)]
5100 step
Cost: 0.04402727261185646
Weight:
[array([[-5.4185824, -4.4528294],
       [-5.4171433, -4.4524217]], dtype=float32), array([[-8.550307 ],
       [ 7.7770386]], dtype=float32)]
5200 step
Cost: 0.042367808520793915
Weight:
[array([[-5.4458895, -4

9600 step
Cost: 0.015246326103806496
Weight:
[array([[-6.10779  , -5.1424456],
       [-6.1070867, -5.1422668]], dtype=float32), array([[-10.445956],
       [  9.802155]], dtype=float32)]
9700 step
Cost: 0.015019385144114494
Weight:
[array([[-6.1167397, -5.15148  ],
       [-6.116043 , -5.151304 ]], dtype=float32), array([[-10.4728365],
       [  9.830468 ]], dtype=float32)]
9800 step
Cost: 0.014798885211348534
Weight:
[array([[-6.125548 , -5.160373 ],
       [-6.124858 , -5.1601987]], dtype=float32), array([[-10.499351],
       [  9.858386]], dtype=float32)]
9900 step
Cost: 0.014584594406187534
Weight:
[array([[-6.1342196, -5.169129 ],
       [-6.133535 , -5.1689563]], dtype=float32), array([[-10.525511],
       [  9.885919]], dtype=float32)]
10000 step
Cost: 0.014376205392181873
Weight:
[array([[-6.142756 , -5.1777515],
       [-6.142077 , -5.177581 ]], dtype=float32), array([[-10.551319],
       [  9.913076]], dtype=float32)]

Hypothesis:
[[0.01180657]
 [0.98711234]
 [0.9871132 ]
 [

Neural Network 를 이용해 XOR 문제 해결!

## Wide Neural Network for XOR
아깐 2개 output을 가진 Layer로 했었는데, 이제 더 wide한 Layer 로 해보자!
> wide 한 layer?  
> 한 layer 의 output 이 많다

### wide & deep neural network
- wide: layer의 output 이 많다
![](lec09.assets/image2.png)
<br>
- deep: layer가 많다
![](lec09.assets/image3.png)

In [17]:
# wide layer 
# --> layer1 의 output 수를 10으로, layer2 의 input 수도 동일하게 맞춘다.
# 1st layer
W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

# 2nd layer
W2 = tf.Variable(tf.random_normal([10, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

# cost/loss function
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y) * tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 100 == 0:
            print(f'{step} step\nCost: {sess.run(cost, feed_dict={X:x_data, Y:y_data})}\nWeight:\n{sess.run([W1, W2])}')
    
    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X:x_data, Y:y_data})
    print(f'\nHypothesis:\n{h}\nCorrect:\n{c}\nAccuracy:\n{a}')
            

0 step
Cost: 1.6083478927612305
Weight:
[array([[ 0.45406917,  0.46072277, -0.7974312 , -0.4449723 ,  0.05954427,
         0.46753585,  0.01441014, -1.3744291 ,  2.1541648 ,  2.5299935 ],
       [ 0.45773315, -1.2087803 ,  0.08176854,  0.11274616,  0.9163634 ,
        -0.7038257 ,  1.5770147 , -1.0540137 ,  1.4015211 ,  1.1818751 ]],
      dtype=float32), array([[ 0.967129  ],
       [ 0.7654298 ],
       [ 1.1279694 ],
       [ 0.54853296],
       [ 0.15963417],
       [ 1.3138214 ],
       [-1.2159086 ],
       [ 0.5875422 ],
       [-0.35600412],
       [ 2.4112647 ]], dtype=float32)]
100 step
Cost: 0.6660808324813843
Weight:
[array([[ 0.3058093 ,  0.37414235, -0.9298329 , -0.50692105,  0.07744291,
         0.30942425, -0.07642879, -1.382019  ,  2.138725  ,  2.5659478 ],
       [ 0.40082136, -1.2626109 ,  0.13766111,  0.11172366,  0.9107715 ,
        -0.80990654,  1.5994847 , -1.013549  ,  1.3064104 ,  1.602994  ]],
      dtype=float32), array([[ 0.599452  ],
       [ 0.3101025 ],
 

1600 step
Cost: 0.14791719615459442
Weight:
[array([[-0.20050588,  0.2682161 , -3.406683  , -1.213736  ,  0.60725707,
         0.19758499, -2.6474504 , -1.410578  ,  2.1822336 ,  4.4449387 ],
       [ 0.280146  , -1.3516192 ,  1.9780221 ,  0.42204627,  1.0013556 ,
        -1.2708292 ,  3.8893003 , -0.66739315, -0.30756396,  4.6464543 ]],
      dtype=float32), array([[ 0.20998825],
       [ 0.22375259],
       [ 3.6234584 ],
       [ 1.0451697 ],
       [-1.2933716 ],
       [ 1.0030136 ],
       [-4.5690227 ],
       [ 0.8700201 ],
       [-1.7005693 ],
       [ 5.134638  ]], dtype=float32)]
1700 step
Cost: 0.1315488964319229
Weight:
[array([[-0.2088659 ,  0.2643686 , -3.528555  , -1.2504873 ,  0.62458724,
         0.21023755, -2.7577426 , -1.4167016 ,  2.2140987 ,  4.510634  ],
       [ 0.27590573, -1.3591495 ,  2.0728605 ,  0.43750948,  1.0118068 ,
        -1.2929816 ,  4.0117455 , -0.65874547, -0.39019495,  4.7071195 ]],
      dtype=float32), array([[ 0.20828377],
       [ 0.2520052

3100 step
Cost: 0.04326911270618439
Weight:
[array([[-0.2652628 ,  0.24097352, -4.4416203 , -1.5635959 ,  0.7424681 ,
         0.37523255, -3.6242979 , -1.4672152 ,  2.631092  ,  5.0312214 ],
       [ 0.24035275, -1.4598173 ,  2.8635771 ,  0.5761299 ,  1.1530337 ,
        -1.5244546 ,  4.974328  , -0.6750656 , -0.9390689 ,  5.1527696 ]],
      dtype=float32), array([[ 0.2106985],
       [ 0.5581116],
       [ 5.163211 ],
       [ 1.3915935],
       [-1.7518203],
       [ 1.3203473],
       [-6.404311 ],
       [ 1.3582665],
       [-2.3705156],
       [ 6.279451 ]], dtype=float32)]
3200 step
Cost: 0.04098440334200859
Weight:
[array([[-0.26742867,  0.24054115, -4.478176  , -1.5780741 ,  0.7477365 ,
         0.3845402 , -3.6600428 , -1.4695475 ,  2.654095  ,  5.0528035 ],
       [ 0.2388041 , -1.4658669 ,  2.8980603 ,  0.58319557,  1.1612855 ,
        -1.5369151 ,  5.0136137 , -0.67942876, -0.9597392 ,  5.1707406 ]],
      dtype=float32), array([[ 0.21142916],
       [ 0.5735672 ],
     

4700 step
Cost: 0.022018443793058395
Weight:
[array([[-0.29027843,  0.24087517, -4.8606234 , -1.7424346 ,  0.8123459 ,
         0.49571234, -4.038561  , -1.4962548 ,  2.9195087 ,  5.2811866 ],
       [ 0.22206941, -1.5404611 ,  3.2701523 ,  0.6688181 ,  1.2609441 ,
        -1.6876234 ,  5.4233737 , -0.74690115, -1.1862192 ,  5.3615465 ]],
      dtype=float32), array([[ 0.2219482],
       [ 0.7483015],
       [ 5.916564 ],
       [ 1.568962 ],
       [-1.9842685],
       [ 1.5211369],
       [-7.3296337],
       [ 1.6097945],
       [-2.7010727],
       [ 6.8201246]], dtype=float32)]
4800 step
Cost: 0.02131836488842964
Weight:
[array([[-0.29138502,  0.24116461, -4.878888  , -1.7509443 ,  0.81598186,
         0.5016932 , -4.0568657 , -1.4976501 ,  2.933254  ,  5.2922225 ],
       [ 0.22124603, -1.54457   ,  3.2884228 ,  0.67352355,  1.2663351 ,
        -1.6958531 ,  5.442847  , -0.7512072 , -1.1977552 ,  5.3708186 ]],
      dtype=float32), array([[ 0.22257644],
       [ 0.75722903],
    

6400 step
Cost: 0.013912196271121502
Weight:
[array([[-0.3053968 ,  0.24754915, -5.107243  , -1.863276  ,  0.8670589 ,
         0.582294  , -4.2877135 , -1.5162753 ,  3.1127706 ,  5.431385  ],
       [ 0.2107716 , -1.6005185 ,  3.5206203 ,  0.738105  ,  1.3388727 ,
        -1.8079247 ,  5.685269  , -0.81446344, -1.3500408 ,  5.488355  ]],
      dtype=float32), array([[ 0.23132797],
       [ 0.8732732 ],
       [ 6.4027452 ],
       [ 1.6892383 ],
       [-2.142039  ],
       [ 1.6637104 ],
       [-7.9243083 ],
       [ 1.7781558 ],
       [-2.9245877 ],
       [ 7.164279  ]], dtype=float32)]
6500 step
Cost: 0.013605444692075253
Weight:
[array([[-0.30610007,  0.24801338, -5.1185527 , -1.8691438 ,  0.86988837,
         0.58658385, -4.299248  , -1.5172617 ,  3.122021  ,  5.4383388 ],
       [ 0.21024446, -1.6035178 ,  3.5323012 ,  0.74160266,  1.3427182 ,
        -1.8139427 ,  5.6972218 , -0.8180731 , -1.3580147 ,  5.494263  ]],
      dtype=float32), array([[ 0.23180297],
       [ 0.8792

8000 step
Cost: 0.010153737850487232
Weight:
[array([[-0.31509158,  0.25529712, -5.261779  , -1.9461739 ,  0.9085483 ,
         0.64361364, -4.4462633 , -1.5304366 ,  3.2420259 ,  5.527018  ],
       [ 0.20350415, -1.6434759 ,  3.681734  ,  0.78863734,  1.393574  ,
        -1.8943012 ,  5.8481565 , -0.8679851 , -1.4630346 ,  5.5698614 ]],
      dtype=float32), array([[ 0.23813821],
       [ 0.95648706],
       [ 6.7250185 ],
       [ 1.7720004 ],
       [-2.2508256 ],
       [ 1.7638245 ],
       [-8.317122  ],
       [ 1.8928971 ],
       [-3.0788205 ],
       [ 7.3915544 ]], dtype=float32)]
8100 step
Cost: 0.009980792179703712
Weight:
[array([[-0.31560615,  0.25579187, -5.269899  , -1.9506975 ,  0.9109062 ,
         0.6470038 , -4.45465   , -1.531224  ,  3.248985  ,  5.532081  ],
       [ 0.20311858, -1.6458535 ,  3.6902893 ,  0.79146343,  1.3965787 ,
        -1.8990945 ,  5.856687  , -0.8710551 , -1.4692231 ,  5.574192  ]],
      dtype=float32), array([[ 0.23851456],
       [ 0.9609

9600 step
Cost: 0.007916515693068504
Weight:
[array([[-0.3224081 ,  0.263214  , -5.3764477 , -2.011706  ,  0.9436541 ,
         0.6931896 , -4.56527   , -1.5420694 ,  3.3418207 ,  5.598895  ],
       [ 0.19802853, -1.6782205 ,  3.8033917 ,  0.83025926,  1.4372528 ,
        -1.964476  ,  5.968384  , -0.9138509 , -1.5529284 ,  5.6315503 ]],
      dtype=float32), array([[ 0.24361688],
       [ 1.0207238 ],
       [ 6.973447  ],
       [ 1.8376368 ],
       [-2.3372233 ],
       [ 1.84413   ],
       [-8.619225  ],
       [ 1.9832783 ],
       [-3.2014368 ],
       [ 7.566743  ]], dtype=float32)]
9700 step
Cost: 0.007806835696101189
Weight:
[array([[-0.32280946,  0.26370275, -5.3826904 , -2.0153785 ,  0.94568115,
         0.6959975 , -4.571784  , -1.542737  ,  3.3473465 ,  5.6028323 ],
       [ 0.1977286 , -1.6801853 ,  3.810067  ,  0.83263457,  1.439709  ,
        -1.968453  ,  5.9749136 , -0.91650635, -1.5579811 ,  5.6349406 ]],
      dtype=float32), array([[ 0.24392499],
       [ 1.0242

**효과**: Hypothesis 의 값이 0과 1에 더 가깝게 변함

## Deep Neural Network for XOR
이번엔 layer 수를 늘려서 Deep 한 모델로 만들어보자

In [19]:
# 1st layer
W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

# 2nd layer
W2 = tf.Variable(tf.random_normal([10, 10]), name='weight2')
b2 = tf.Variable(tf.random_normal([10]), name='bias2')
layer2 = tf.sigmoid(tf.matmul(layer1, W2) + b2)

# 3rd layer
W3 = tf.Variable(tf.random_normal([10, 10]), name='weight3')
b3 = tf.Variable(tf.random_normal([10]), name='bias3')
layer3 = tf.sigmoid(tf.matmul(layer2, W3) + b3)

# 4th layer
W4 = tf.Variable(tf.random_normal([10, 1]), name='weight4')
b4 = tf.Variable(tf.random_normal([1]), name='bias4')
hypothesis = tf.sigmoid(tf.matmul(layer3, W4) + b4)


# cost/loss function
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y) * tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 100 == 0:
            print(f'{step} step\nCost: {sess.run(cost, feed_dict={X:x_data, Y:y_data})}\n')
    
    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X:x_data, Y:y_data})
    print(f'\nHypothesis:\n{h}\nCorrect:\n{c}\nAccuracy:\n{a}')
            

0 step
Cost: 0.8155993819236755

100 step
Cost: 0.6945605278015137

200 step
Cost: 0.6937944889068604

300 step
Cost: 0.6930364370346069

400 step
Cost: 0.6922515034675598

500 step
Cost: 0.6914016008377075

600 step
Cost: 0.6904414892196655

700 step
Cost: 0.6893143653869629

800 step
Cost: 0.6879439353942871

900 step
Cost: 0.6862237453460693

1000 step
Cost: 0.683999240398407

1100 step
Cost: 0.6810394525527954

1200 step
Cost: 0.6769937872886658

1300 step
Cost: 0.6713297367095947

1400 step
Cost: 0.6632473468780518

1500 step
Cost: 0.6515330672264099

1600 step
Cost: 0.6342103481292725

1700 step
Cost: 0.6077064871788025

1800 step
Cost: 0.5653380155563354

1900 step
Cost: 0.4961300790309906

2000 step
Cost: 0.3907792568206787

2100 step
Cost: 0.26567715406417847

2200 step
Cost: 0.16499270498752594

2300 step
Cost: 0.10448922216892242

2400 step
Cost: 0.07080839574337006

2500 step
Cost: 0.05129405856132507

2600 step
Cost: 0.039202455431222916

2700 step
Cost: 0.0312204007059335

**효과**: 전보다 더 hypothesis 값이 0과 1에 가깝게 나왔다.