# Lec 06-1. Tensorflow 로 Softmax Classification 구현하기

![](lec06.assets/image1.png)

**hypothesis** = tf.nn.**softmax**(tf.matmul(X,W)+b)  
위 그림에서 scores 를 <u>**'logit'**</u> 이라고도 한다

![](lec06.assets/image2.png)

**cost(cross-entropy)** = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

In [1]:
import tensorflow as tf

In [9]:
x_data = [[1,2,1,1],
          [2,1,3,2],
          [3,1,3,4],
          [4,1,5,5],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7]]
y_data = [[0,0,1],  # 2
          [0,0,1],  
          [0,0,1],  
          [0,1,0],  # 1
          [0,1,0],
          [0,1,0],
          [0,0,1],  # 0 
          [0,0,1]]

X = tf.placeholder('float', [None, 4])
Y = tf.placeholder('float', [None, 3])  # 3 class
n_classes = 3

W = tf.Variable(tf.random_normal([4, n_classes]), name='weight')
b = tf.Variable(tf.random_normal([n_classes]), name='bias')

# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step % 200 == 0:
            print(f'{step} step\n  Cost: {sess.run(cost, feed_dict={X:x_data, Y:y_data})}')
                                          
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(f'\n\n{a},\n one-hot encoding: {sess.run(tf.arg_max(a, 1))}')
  
    _all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9],
                                              [1, 3, 4, 3],
                                              [1, 1, 0, 1]]})
    print(f'\n\n{_all},\n one-hot encoding: {sess.run(tf.arg_max(_all, 1))}')

0 step
  Cost: 4.536135673522949
200 step
  Cost: 0.8091461062431335
400 step
  Cost: 0.8072640895843506
600 step
  Cost: 0.8073461055755615
800 step
  Cost: 0.8078129291534424
1000 step
  Cost: 0.8083454966545105
1200 step
  Cost: 0.808843195438385
1400 step
  Cost: 0.8092769980430603
1600 step
  Cost: 0.8096445798873901
1800 step
  Cost: 0.8099514842033386
2000 step
  Cost: 0.8102056980133057


[[1.1198183e-07 9.6585453e-01 3.4145337e-02]],
 one-hot encoding: [1]


[[1.11982025e-07 9.65854406e-01 3.41453999e-02]
 [4.98533365e-04 2.40798712e-01 7.58702815e-01]
 [1.14750781e-03 7.96737224e-02 9.19178843e-01]],
 one-hot encoding: [1 2 2]
